export const LOAD_WALLPAPERS = "LOAD_WALLPAPERS";

export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const DOWNLOAD_COMPLETED_VISIBLE = "DOWNLOAD_COMPLETED_VISIBLE";
export const DOWNLOAD_COMPLETED_INVISIBLE = "DOWNLOAD_COMPLETED_INVISIBLE";
