export const LOAD_FONTS = "LOAD_FONTS";

export const LOAD_WALLPAPERS = "LOAD_WALLPAPERS";

export const OPEN_DETAILS = "OPEN_DETAILS";
export const CLOSE_DETAILS = "CLOSE_DETAILS";

export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";

export const OPEN_SIDE_DRAWER = "OPEN_SIDE_DRAWER";
export const CLOSE_SIDE_DRAWER = "CLOSE_SIDE_DRAWER";
